Première version RampAccessScheduleTable
Monitoring-Mtl/Frontend pull request #56
Opened 2023-11-20 23:13 UTC by VincentBerube

added RampAccessScheduleTable component, placed it next to the line selectform

Here is the previous layout :
![image](https://github.com/Monitoring-Mtl/Frontend/assets/60930615/3f5c3a7b-792e-4047-b5cb-2ed1ba72a1a3)

and here is the new layout : 
![image](https://github.com/Monitoring-Mtl/Frontend/assets/60930615/6769f885-dbc1-4dfc-8cb8-f4be5f028668)

Still to be done : make sure the schedule update when a route is selected, improve the overall layout

![image](https://github.com/Monitoring-Mtl/Frontend/assets/60930615/9d10e60b-74fe-4a33-901d-4473c43b3756)

2023-11-20 23:18 UTC, SimonVoyer requested changes
Faudrait que tu changes la branche ciblée pour develop. Va probablement aussi falloir régler quelques conflits.

2023-11-23 22:31 UTC, VincentBerube commented
> Faudrait que tu changes la branche ciblée pour develop. Va probablement aussi falloir mettre à jour ta branche et régler quelques conflits.

fixed

2023-11-24 00:08 UTC, SimonVoyer approved these changes
Comme on a discuté je mettrais juste l'horaire à côté du graphique pour l'accès aux rampes. On ajustera au besoin dans les prochains jours

2023-11-29 04:50 UTC, hanhlongdo requested changes
Prendre des captures d'écrans des checks (Cypress tests spécifiquement) pour documenter le power-point de la présentation finale.

2023-12-01 00:29 UTC, hanhlongdo approved these changes
Simon va faire les screenshots avec sa PR

2023-12-03 14:51 UTC, SimonVoyer commented
On ne va pas aller de l'avant avec cette feature pour l'instant. Au besoin on va réouvrir la PR.

2023-12-03 14:51 UTC, closed without merging