disable button when form is not complete
Monitoring-Mtl/Frontend pull request #91
Opened 2023-12-10 21:07 UTC by VincentBerube

### 🛠  Why are these changes being made? / Quel est l'objectif du changement?

Clarifier l'UI afin d'indiquer clairement que tous les champs doivent être remplie avant de permettre l'analyse

### 🧠 How are these changes made? / Comment as-tu implémenté ce changement?

En rajoutant un prop isDisabled? à notre composant de boutton et en utilisant les propriété isDirty et isValid des forms Formik, pour vérifier si les tous les champs sont remplies correctement

### 📸 Screenshots (optional)

Avant:
![image](https://github.com/Monitoring-Mtl/Frontend/assets/60930615/46615d84-ceaf-41ab-b6da-cb11713e7828)

Après:
![image](https://github.com/Monitoring-Mtl/Frontend/assets/60930615/ec974bc3-1720-4e05-a150-22354e1feec0)

2023-12-10 21:57 UTC, hanhlongdo commented
À la première passe c'est bon mais quand je rechange la ligne d'autobus à la 2e fois, la direction reset et le bouton est actif alors qu'il ne devrait pas: 
![image](https://github.com/Monitoring-Mtl/Frontend/assets/60677723/925dcdcd-422f-4d2c-bcf8-b83e2d6e4166)

2023-12-10 21:58 UTC, hanhlongdo requested changes
À la première passe c'est bon mais quand je rechange la ligne d'autobus à la 2e fois, la direction reset et le bouton est actif alors qu'il ne devrait pas:
![image](https://github.com/Monitoring-Mtl/Frontend/assets/60677723/884d4822-7261-4a21-b270-fd74398a0780)

2023-12-12 00:08 UTC, VincentBerube commented
Fix l'issue pour le changement de ligne et de direction

2023-12-12 00:52 UTC, hanhlongdo approved these changes
Test concluant sur Amplify.

2023-12-12 00:54 UTC, hanhlongdo requested changes
Une j'ai vu de quoi dans les tests, je dois confirmer

2023-12-12 01:02 UTC, hanhlongdo approved these changes
Test concluant sur Amplify

2023-12-12 01:03 UTC, merged